<x-auditor.layout :title="$order->number . ' - Audytor IT'">
    <div class="page-head"><div class="stack"><a class="button secondary" href="{{ route('delivery.audit-orders.index') }}" style="width:max-content;color:var(--text);border-color:var(--line);">Wroc</a><h1>{{ $order->number }}</h1><strong>{{ $order->title }}</strong><div class="muted">{{ $order->client->name }}{{ $order->location ? ' / '.$order->location->name : '' }} / {{ $order->auditType->name }} v{{ $order->versionDefinition->version }}</div><div class="meta"><span class="pill {{ $order->status->color() }}">{{ $order->status->label() }}</span><span class="pill">{{ $order->planned_hours }} / {{ $order->expected_hours }} h</span><span class="pill">Min. kompetencje: {{ $order->minimum_competency_level?->label() ?? '-' }}</span></div></div></div>
    @if(session('status'))<div class="notice" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="error" style="margin-bottom:16px;">{{ $errors->first() }}</div>@endif
    @if($order->technicalAudit)<div class="notice" style="margin-bottom:16px;">Audyt techniczny: <strong>{{ $order->technicalAudit->number }}</strong> / status {{ $order->technicalAudit->status->label() }} / postep {{ $order->technicalAudit->progress_percent }}%@unless(auth()->user()->hasRole(\App\Enums\UserRole::Sales)) / <a href="{{ route('engineer.audits.show',$order->technicalAudit) }}">otworz</a>@endunless</div>@endif

    @if($order->readinessBlockers() !== [])<section class="error" style="margin-bottom:18px;"><strong>Blokery gotowosci</strong><ul>@foreach($order->readinessBlockers() as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></section>@endif

    <section class="card" style="margin-bottom:18px;"><h2>Informacje sprzedazowe</h2><div class="grid"><div><strong>Cel</strong><div class="muted">{{ $order->purpose ?: '-' }}</div></div><div><strong>Zakres</strong><div class="muted">{{ $order->scope_summary ?: '-' }}</div></div><div><strong>Zalozenia</strong><div class="muted">{{ $order->assumptions ?: '-' }}</div></div><div><strong>Wylaczenia</strong><div class="muted">{{ $order->exclusions ?: '-' }}</div></div><div><strong>Kontakt</strong><div class="muted">{{ $order->client_contact_name ?: '-' }} / {{ $order->client_contact_email ?: '-' }} / {{ $order->client_contact_phone ?: '-' }}</div></div><div><strong>Wycena</strong><div class="muted">{{ $order->quotation->net_price }} {{ $order->quotation->currency }} netto / {{ $order->expected_hours }} h</div></div></div><div class="meta"><a class="button" href="{{ route('sales.quotations.show', $order->quotation) }}">Wycena {{ $order->quotation->number }}</a><a class="button" href="{{ route('sales.qualifications.show', $order->qualification) }}">Kwalifikacja #{{ $order->qualification->id }}</a></div></section>

    <section class="card" style="margin-bottom:18px;"><h2>Konfiguracja audytu</h2>@php($configuration = $order->configuration_snapshot)<div class="grid"><div><strong>Typ i wersja</strong><div class="muted">{{ $order->auditType->name }} / v{{ data_get($configuration, 'version.version') }}</div></div><div><strong>Moduly techniczne</strong><div class="muted">{{ count($configuration['technical_modules'] ?? []) }}</div></div><div><strong>Kontrole</strong><div class="muted">{{ collect($configuration['technical_modules'] ?? [])->sum(fn($module) => count($module['controls'] ?? $module['control_definitions'] ?? [])) }}</div></div><div><strong>Czasy</strong><div class="muted">Przygotowanie {{ data_get($configuration, 'version.estimated_preparation_minutes', 0) }} min / realizacja {{ data_get($configuration, 'version.estimated_execution_minutes', 0) }} min / raport {{ data_get($configuration, 'version.estimated_reporting_minutes', 0) }} min / przeglad {{ data_get($configuration, 'version.estimated_review_minutes', 0) }} min</div></div></div><div><strong>Instrukcje Delivery</strong><div class="muted">{{ $order->delivery_instructions ?: '-' }}</div></div></section>

    <section class="card" style="margin-bottom:18px;"><h2>Plan realizacji</h2>@if($canPlan)<form class="stack" method="post" action="{{ route('delivery.audit-orders.plan', $order) }}">@csrf @method('patch')<div class="grid"><label>Start<input type="datetime-local" name="planned_start_at" value="{{ $order->planned_start_at?->format('Y-m-d\TH:i') }}"></label><label>Koniec<input type="datetime-local" name="planned_end_at" value="{{ $order->planned_end_at?->format('Y-m-d\TH:i') }}"></label><label>Planowane godziny<input type="number" name="planned_hours" min="0" step="0.25" value="{{ $order->planned_hours }}" required></label></div><label>Notatki planistyczne<textarea name="planning_notes">{{ $order->planning_notes }}</textarea></label><button style="width:max-content;" type="submit">Zapisz plan</button></form>@else<div class="grid"><div><strong>Termin</strong><div>{{ $order->planned_start_at?->format('Y-m-d H:i') ?? '-' }} - {{ $order->planned_end_at?->format('Y-m-d H:i') ?? '-' }}</div></div><div><strong>Notatki</strong><div>{{ $order->planning_notes ?: '-' }}</div></div></div>@endif</section>

    <section class="card" style="margin-bottom:18px;"><h2>Zespol</h2>@if($canPlan)<form class="grid" method="post" action="{{ route('delivery.audit-orders.assignees.store', $order) }}">@csrf<label>Osoba<select name="user_id" required>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} / {{ $user->role->label() }} / {{ $user->competency_level?->label() ?? 'brak poziomu' }}</option>@endforeach</select></label><label>Rola<select name="assignment_role" required>@foreach($roles as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Godziny<input type="number" name="planned_hours" step="0.25" min="0" value="0"></label><label>Notatki<input name="notes"></label><div style="align-self:end;"><button type="submit">Przypisz</button></div></form>@endif<div class="attachments">@forelse($order->assignees as $assignee)<div class="attachment-row"><div><strong>{{ $assignee->user->name }}</strong><div class="muted">{{ $roles[$assignee->assignment_role] }} / {{ $assignee->planned_hours ?? 0 }} h / {{ $assignee->competency_level?->label() ?? 'brak poziomu' }}</div></div>@if($canPlan)<form method="post" action="{{ route('delivery.audit-orders.assignees.destroy', [$order, $assignee]) }}">@csrf @method('delete')<button type="submit">Usun</button></form>@endif</div>@empty<div class="muted">Brak przypisan.</div>@endforelse</div></section>

    <section class="card" style="margin-bottom:18px;"><h2>Checklista przygotowania</h2><div class="stack">@foreach($order->preparationItems as $item)<form class="card" style="box-shadow:none;" method="post" action="{{ route('delivery.audit-orders.preparation.update', [$order, $item]) }}">@csrf @method('patch')<div><strong>{{ $item->title }}</strong><div class="muted">{{ $item->category }} / {{ $item->required ? 'wymagane' : 'opcjonalne' }}</div></div>@if($canPlan)<div class="grid"><label>Status<select name="status">@foreach($itemStatuses as $value => $label)<option value="{{ $value }}" @selected($item->status === $value)>{{ $label }}</option>@endforeach</select></label><label>Notatki<input name="notes" value="{{ $item->notes }}"></label><div style="align-self:end;"><button>Zapisz</button></div></div>@else<span class="pill">{{ $itemStatuses[$item->status] }}</span>@endif</form>@endforeach</div></section>

    <section class="card" style="margin-bottom:18px;"><h2>Dokumenty</h2>@if($canPlan)<form class="grid" method="post" enctype="multipart/form-data" action="{{ route('delivery.audit-orders.documents.store', $order) }}">@csrf<label>Kategoria<select name="category">@foreach($documentCategories as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Plik<input type="file" name="document" required></label><div style="align-self:end;"><button>Dodaj dokument</button></div></form>@endif<div class="attachments">@forelse($order->documents as $document)<div class="attachment-row"><div><strong>{{ $document->original_name }}</strong><div class="muted">{{ $documentCategories[$document->category] ?? $document->category }} / {{ number_format($document->size_bytes / 1024, 1) }} KB{{ $document->isSourceReference() ? ' / z kwalifikacji' : '' }}</div></div><a class="button" href="{{ route('delivery.audit-orders.documents.download', [$order, $document]) }}">Pobierz</a>@if($canPlan && !$document->isSourceReference())<form method="post" action="{{ route('delivery.audit-orders.documents.destroy', [$order, $document]) }}">@csrf @method('delete')<button>Usun</button></form>@endif</div>@empty<div class="muted">Brak dokumentow.</div>@endforelse</div></section>

    @if($canPlan && $order->status->allowedTransitions() !== [])<section class="card" style="margin-bottom:18px;"><h2>Workflow</h2><div class="meta">@foreach($order->status->allowedTransitions() as $target)<form method="post" action="{{ route('delivery.audit-orders.transition', [$order, $target->value]) }}">@csrf @if($target === \App\Enums\AuditOrderStatus::Cancelled)<input name="reason" required placeholder="Powod anulowania">@endif @if($target === \App\Enums\AuditOrderStatus::Scheduled)<input name="justification" placeholder="Uzasadnienie terminu historycznego">@endif<button type="submit">{{ $target->label() }}</button></form>@endforeach</div></section>@endif

    <section class="card"><h2>Historia</h2>@forelse($order->auditLogs as $log)<div><strong>{{ $log->event }}</strong><div class="muted">{{ $log->actor?->name ?? 'System' }} / {{ $log->created_at->format('Y-m-d H:i') }}</div></div>@empty<div class="muted">Brak zdarzen.</div>@endforelse</section>
</x-auditor.layout>
